/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDepensesRouteImport } from './routes/_app.depenses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppAvancesRouteImport } from './routes/_app.avances'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAvancesRoute = AppAvancesRouteImport.update({
  id: '/avances',
  path: '/avances',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avances': typeof AppAvancesRoute
  '/categories': typeof AppCategoriesRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/depenses': typeof AppDepensesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avances': typeof AppAvancesRoute
  '/categories': typeof AppCategoriesRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/depenses': typeof AppDepensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/avances': typeof AppAvancesRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/depenses': typeof AppDepensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avances'
    | '/categories'
    | '/contacts'
    | '/dashboard'
    | '/depenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avances'
    | '/categories'
    | '/contacts'
    | '/dashboard'
    | '/depenses'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/avances'
    | '/_app/categories'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/depenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/depenses': {
      id: '/_app/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avances': {
      id: '/_app/avances'
      path: '/avances'
      fullPath: '/avances'
      preLoaderRoute: typeof AppAvancesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAvancesRoute: typeof AppAvancesRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepensesRoute: typeof AppDepensesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvancesRoute: AppAvancesRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepensesRoute: AppDepensesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
